{% set version = "2.0.1" %}

package:
  name: cf_units
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cf_units/cf_units-{{ version }}.tar.gz
  sha256: aeb4978c11518bcb2516c1cf7beb053d1be0cd8e2349a07ad78094f63a2837f4

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - udunits2 >=2.2.23
  run:
    - python
    - numpy >=1.11
    - udunits2 >=2.2.23
    - cftime
    - six

test:
  source_files:
    - cf_units/tests
  requires:
    - pytest
    - pep8
  imports:
    - cf_units
  commands:
    - cd cf_units && python -m pytest tests
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.scitools.org.uk/iris
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Units of measure as required by the Climate and Forecast (CF) metadata conventions.'

extra:
  recipe-maintainers:
    - bjlittle
    - dkillick
    - ocefpaf
    - pelson
