{% set version = "1.1.1" %}

package:
    name: cf_units
    version: {{ version }}

source:
    fn: cf_units-{{ version }}.tar.gz
    url: https://github.com/SciTools/cf_units/archive/v{{ version }}.tar.gz
    sha256: a535d0418facc7c38d201312811c54d63b578f2d35c3818395b3427468d6b791

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - six
        - udunits2
        - netcdf4
        - numpy

test:
    imports:
        - cf_units

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: Units of measure as required by the Climate and Forecast (CF) metadata conventions.

extra:
    recipe-maintainers:
        - bjlittle
        - dkillick
        - ocefpaf
        - pelson
