{% set version = "1.1.3" %}

package:
  name: cf_units
  version: {{ version }}

source:
  url: https://github.com/SciTools/cf_units/archive/v{{ version }}.tar.gz
  sha256: 3705ea3bb083ce59d0c113c25221c91e7d0ce286e2996c209942adaf93c3bcdd

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - udunits2 >=2.2.23
    - netcdf4
    - numpy

test:
  imports:
    - cf_units

about:
  home: http://www.scitools.org.uk/iris
  license: LGPL-3.0
  license_file: COPYING.LESSER
  summary: 'Units of measure as required by the Climate and Forecast (CF) metadata conventions.'

extra:
  recipe-maintainers:
    - bjlittle
    - dkillick
    - ocefpaf
    - pelson
