travis:
  secure:
    BINSTAR_TOKEN: og5ZCVM3nb0SzyQrVBCUOo0isMo/1a8Q2uBD9yu8WT42r3NgUA3+6iE0tfoLg8BofYrr4ZpWN8h+DHLVWnOYnWTyIZyHBD2c9b9GoccGhoo6EtKQWOqosmdT/mBLT5BVFevpcihposGS9mlAVyfj3atZDw5TaEp8wCzy1aquWZZNx6dYEj5gkeaf+z3pmkXtpA5NtEz4nAnni+nFQOw5LNaFPJuRdFx4YflJCVZ4s/iCIJurwB9CRXwuraMvI3ATX0xciKggCO2+8HnBcGdku/XqrxnHq1ruAlleAskJIvo2RLZniB2lKSW6VqdS92cshF9btpOwwqsqecRvHTzkk5rqJmFMxYQCxFkrMekd1EE5c8q495IJsVGvkRAFGbebVlOfYn5PN4L/KgFY+lqJvhVr4LYMUJ/b2nKLJtUfOi98ugXrUVHmIWhZdszrKxO4hjKcpJJHbRlrr7aEMgrD5uswzMCwQQ6ZKKaA9SffYTRWvJQAF4Civy3OxAMUMh89LDoxZixZg4z0VpugVKZ/j/lOkqZ8sJPWaQfaxQFc4c4XnKp400o/DpMFexlvQ+aHaS4lOcmQ3OhofS2fE9kL5o3nTtfeq1XAE3WQecuoR9hZkiq1pNlC7z3sFeunoLlkqLoyrXU6ztaVNYgWliZIGly/5OpsZf745eo8opX/DrA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
